#
# Configuration de Camix.
#
# Author : Matthias Brun
# version : 0.5
#

# Port de connexion au serveur
PORT_SERVICE_CHAT = 12345

# Nom du canal par défaut
CANAL_PAR_DEFAUT = place publique

# Surnom par défaut d'un client
SURNOM_CLIENT_DEFAUT = ?

